/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    services: Service;
    locations: Location;
    'pillar-pages': PillarPage;
    'state-pages': StatePage;
    'city-pages': CityPage;
    leads: Lead;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'pillar-pages': PillarPagesSelect<false> | PillarPagesSelect<true>;
    'state-pages': StatePagesSelect<false> | StatePagesSelect<true>;
    'city-pages': CityPagesSelect<false> | CityPagesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Service name (e.g., "Payday Loans")
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  category:
    | 'short-term'
    | 'digital'
    | 'flexible'
    | 'urgent'
    | 'credit-flexible'
    | 'emergency'
    | 'personal'
    | 'fast-approval';
  /**
   * Brief description (max 200 chars)
   */
  shortDescription: string;
  /**
   * Detailed service description
   */
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Key benefits of this service
   */
  benefits?:
    | {
        benefit: string;
        id?: string | null;
      }[]
    | null;
  loanAmounts?: {
    /**
     * Minimum loan amount in dollars
     */
    min?: number | null;
    /**
     * Maximum loan amount in dollars
     */
    max?: number | null;
    /**
     * Display text (e.g., "$100 - $2,500")
     */
    description?: string | null;
  };
  terms?: {
    /**
     * Repayment terms description
     */
    description?: string | null;
    examples?:
      | {
          term?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Eligibility requirements
   */
  requirements?:
    | {
        requirement: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Frequently asked questions
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * SEO title (max 70 chars)
   */
  seoTitle?: string | null;
  /**
   * Meta description (max 160 chars)
   */
  seoDescription?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility
   */
  alt: string;
  /**
   * Image caption (optional)
   */
  caption?: string | null;
  /**
   * Photo credit/attribution
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  city: string;
  state: string;
  /**
   * Two-letter state code (e.g., TX, CA, FL)
   */
  stateCode: string;
  /**
   * County name for local SEO
   */
  county?: string | null;
  /**
   * City population
   */
  population?: number | null;
  /**
   * Local phone area code (e.g., 214, 713)
   */
  areaCode?: string | null;
  /**
   * Local landmarks (for Anti-Doorway content)
   */
  landmarks?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Major highways (e.g., I-35, US-75)
   */
  highways?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Nearby towns for "Also serving" section
   */
  neighboringTowns?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  coordinates?: {
    /**
     * Latitude
     */
    lat?: number | null;
    /**
     * Longitude
     */
    lng?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillar-pages".
 */
export interface PillarPage {
  id: number;
  /**
   * Page title (e.g., "Payday Loans")
   */
  title: string;
  /**
   * URL slug (e.g., "payday-loans")
   */
  slug: string;
  status?: ('draft' | 'published') | null;
  /**
   * Related service
   */
  service?: (number | null) | Service;
  /**
   * Search Engine Optimization
   */
  seo?: {
    /**
     * SEO title (max 70 chars)
     */
    metaTitle?: string | null;
    /**
     * Meta description (max 160 chars)
     */
    metaDescription?: string | null;
  };
  hero: {
    headline: string;
    subheadline?: string | null;
    ctaText?: string | null;
    ctaUrl?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * What Is [Service] section
   */
  whatIs?: {
    heading?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Key benefits list
   */
  benefits?:
    | {
        title: string;
        description?: string | null;
        /**
         * Icon name or emoji
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Application process steps
   */
  process?:
    | {
        step: number;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Why Choose Lion Cash Advance
   */
  whyChooseUs?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Frequently Asked Questions
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Related services to link to
   */
  relatedServices?: (number | Service)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "state-pages".
 */
export interface StatePage {
  id: number;
  /**
   * Full state name (e.g., "California")
   */
  state: string;
  /**
   * Two-letter code (e.g., "CA")
   */
  stateCode: string;
  /**
   * URL slug (e.g., "california")
   */
  slug: string;
  status?: ('draft' | 'published') | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  hero: {
    headline: string;
    subheadline?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * State overview content
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Regulatory and compliance information for this state
   */
  compliance?: {
    /**
     * Legal status of service in this state
     */
    legalStatus?: string | null;
    /**
     * State regulatory agency
     */
    regulatoryBody?: string | null;
    /**
     * Link to regulatory website
     */
    regulatoryUrl?: string | null;
    /**
     * APR caps, rate limits, fee limits
     */
    rateCaps?: string | null;
    /**
     * Maximum loan amounts, term limits
     */
    loanLimits?: string | null;
    /**
     * Consumer protection laws
     */
    consumerProtections?:
      | {
          protection: string;
          id?: string | null;
        }[]
      | null;
    /**
     * State-specific legal disclaimer
     */
    disclaimer?: string | null;
    /**
     * When compliance info was last verified
     */
    lastUpdated?: string | null;
  };
  /**
   * Cities served in this state
   */
  cities?: (number | Location)[] | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-pages".
 */
export interface CityPage {
  id: number;
  city: string;
  state: string;
  stateCode: string;
  /**
   * URL slug (e.g., "dallas")
   */
  slug: string;
  /**
   * County name for local SEO
   */
  county?: string | null;
  status?: ('draft' | 'published') | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  hero: {
    headline: string;
    subheadline?: string | null;
    /**
     * Real local branch photo (NOT stock images)
     */
    image?: (number | null) | Media;
  };
  /**
   * Local facts that prove genuine local presence - prevents doorway page penalty
   */
  localProof?: {
    /**
     * Local landmarks (e.g., Reunion Tower, Zilker Park)
     */
    landmarks?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Major highways (e.g., I-35E, US-75)
     */
    highways?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Highway exits for directions
     */
    exits?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Paragraph naturally incorporating local facts
     */
    localDescription?: string | null;
  };
  /**
   * State-specific regulatory information
   */
  stateCompliance?: {
    /**
     * Display compliance section on page
     */
    showCompliance?: boolean | null;
    /**
     * State APR/rate cap information
     */
    rateCaps?: string | null;
    /**
     * Consumer protection information
     */
    consumerProtections?: string | null;
    /**
     * Required legal disclaimer
     */
    disclaimer?: string | null;
    regulatoryBody?: string | null;
  };
  /**
   * Services available in this city - link UP to pillar pages
   */
  products?:
    | {
        service: number | Service;
        /**
         * City-specific description for this service
         */
        localDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Customer reviews from this location
   */
  localReviews?:
    | {
        reviewerName: string;
        reviewerCity?: string | null;
        rating: number;
        text: string;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Business contact info - MUST use LOCAL area code!
   */
  nap?: {
    businessName?: string | null;
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    /**
     * MUST use LOCAL area code (e.g., 214-555-1234), NOT 1-800!
     */
    phone?: string | null;
    /**
     * Local area code (214, 713, etc.)
     */
    areaCode?: string | null;
    email?: string | null;
    googleMapsUrl?: string | null;
  };
  /**
   * Also serving these nearby towns
   */
  nearbyLocations?:
    | {
        name: string;
        /**
         * Distance (e.g., "5 miles")
         */
        distance?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * FAQs with local keywords
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    primaryText?: string | null;
    primaryUrl?: string | null;
    secondaryText?: string | null;
    secondaryUrl?: string | null;
  };
  /**
   * Schema.org type for structured data
   */
  schemaType?: ('FinancialService' | 'LocalBusiness' | 'LegalService') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone: string;
  source:
    | 'contact-form'
    | 'quote-request'
    | 'callback-request'
    | 'application'
    | 'manual'
    | 'phone-call'
    | 'walk-in'
    | 'referral';
  /**
   * Requested loan amount
   */
  loanAmount?: number | null;
  loanPurpose?: string | null;
  city?: string | null;
  state?: string | null;
  status: 'new' | 'contacted' | 'qualified' | 'quoted' | 'converted' | 'lost' | 'dnc';
  /**
   * Activity notes
   */
  notes?:
    | {
        note: string;
        addedBy?: string | null;
        addedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Assigned team member
   */
  assignedTo?: (number | null) | User;
  /**
   * Next follow-up date
   */
  nextFollowUp?: string | null;
  lastContactedAt?: string | null;
  /**
   * Page where lead was submitted
   */
  sourceUrl?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'pillar-pages';
        value: number | PillarPage;
      } | null)
    | ({
        relationTo: 'state-pages';
        value: number | StatePage;
      } | null)
    | ({
        relationTo: 'city-pages';
        value: number | CityPage;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  longDescription?: T;
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  loanAmounts?:
    | T
    | {
        min?: T;
        max?: T;
        description?: T;
      };
  terms?:
    | T
    | {
        description?: T;
        examples?:
          | T
          | {
              term?: T;
              id?: T;
            };
      };
  requirements?:
    | T
    | {
        requirement?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  city?: T;
  state?: T;
  stateCode?: T;
  county?: T;
  population?: T;
  areaCode?: T;
  landmarks?:
    | T
    | {
        name?: T;
        id?: T;
      };
  highways?:
    | T
    | {
        name?: T;
        id?: T;
      };
  neighboringTowns?:
    | T
    | {
        name?: T;
        id?: T;
      };
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillar-pages_select".
 */
export interface PillarPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  service?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        ctaText?: T;
        ctaUrl?: T;
        image?: T;
      };
  whatIs?:
    | T
    | {
        heading?: T;
        content?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  process?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  whyChooseUs?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedServices?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "state-pages_select".
 */
export interface StatePagesSelect<T extends boolean = true> {
  state?: T;
  stateCode?: T;
  slug?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        image?: T;
      };
  description?: T;
  compliance?:
    | T
    | {
        legalStatus?: T;
        regulatoryBody?: T;
        regulatoryUrl?: T;
        rateCaps?: T;
        loanLimits?: T;
        consumerProtections?:
          | T
          | {
              protection?: T;
              id?: T;
            };
        disclaimer?: T;
        lastUpdated?: T;
      };
  cities?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-pages_select".
 */
export interface CityPagesSelect<T extends boolean = true> {
  city?: T;
  state?: T;
  stateCode?: T;
  slug?: T;
  county?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        image?: T;
      };
  localProof?:
    | T
    | {
        landmarks?:
          | T
          | {
              name?: T;
              id?: T;
            };
        highways?:
          | T
          | {
              name?: T;
              id?: T;
            };
        exits?:
          | T
          | {
              name?: T;
              id?: T;
            };
        localDescription?: T;
      };
  stateCompliance?:
    | T
    | {
        showCompliance?: T;
        rateCaps?: T;
        consumerProtections?: T;
        disclaimer?: T;
        regulatoryBody?: T;
      };
  products?:
    | T
    | {
        service?: T;
        localDescription?: T;
        id?: T;
      };
  localReviews?:
    | T
    | {
        reviewerName?: T;
        reviewerCity?: T;
        rating?: T;
        text?: T;
        date?: T;
        id?: T;
      };
  nap?:
    | T
    | {
        businessName?: T;
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
        phone?: T;
        areaCode?: T;
        email?: T;
        googleMapsUrl?: T;
      };
  nearbyLocations?:
    | T
    | {
        name?: T;
        distance?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        primaryText?: T;
        primaryUrl?: T;
        secondaryText?: T;
        secondaryUrl?: T;
      };
  schemaType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  source?: T;
  loanAmount?: T;
  loanPurpose?: T;
  city?: T;
  state?: T;
  status?: T;
  notes?:
    | T
    | {
        note?: T;
        addedBy?: T;
        addedAt?: T;
        id?: T;
      };
  assignedTo?: T;
  nextFollowUp?: T;
  lastContactedAt?: T;
  sourceUrl?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName: string;
  tagline?: string | null;
  contact?: {
    /**
     * Main phone number
     */
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    hours?: string | null;
  };
  social?: {
    facebook?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
  };
  seo?: {
    /**
     * Page title template (%s = page title)
     */
    titleTemplate?: string | null;
    defaultDescription?: string | null;
    /**
     * Default Open Graph image
     */
    ogImage?: (number | null) | Media;
  };
  company?: {
    legalName?: string | null;
    foundedYear?: number | null;
    licenses?:
      | {
          license?: string | null;
          id?: string | null;
        }[]
      | null;
    aboutText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  trust?: {
    yearsInBusiness?: string | null;
    customerRating?: string | null;
    reviewCount?: number | null;
    guarantees?:
      | {
          guarantee?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Required legal disclaimers for YMYL compliance
   */
  disclaimers?: {
    /**
     * Disclaimer shown on all pages
     */
    globalDisclaimer?: string | null;
    /**
     * APR disclosure text
     */
    aprDisclosure?: string | null;
    /**
     * Lender relationship disclosure
     */
    lenderDisclosure?: string | null;
    /**
     * State licensing disclosure
     */
    stateDisclosure?: string | null;
  };
  footer?: {
    copyrightText?: string | null;
    additionalText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        hours?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
      };
  seo?:
    | T
    | {
        titleTemplate?: T;
        defaultDescription?: T;
        ogImage?: T;
      };
  company?:
    | T
    | {
        legalName?: T;
        foundedYear?: T;
        licenses?:
          | T
          | {
              license?: T;
              id?: T;
            };
        aboutText?: T;
      };
  trust?:
    | T
    | {
        yearsInBusiness?: T;
        customerRating?: T;
        reviewCount?: T;
        guarantees?:
          | T
          | {
              guarantee?: T;
              id?: T;
            };
      };
  disclaimers?:
    | T
    | {
        globalDisclaimer?: T;
        aprDisclosure?: T;
        lenderDisclosure?: T;
        stateDisclosure?: T;
      };
  footer?:
    | T
    | {
        copyrightText?: T;
        additionalText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}